'use strict';

const MAXIMAL_DMD_FRAMES_TO_RIP = 8000;

const TICKS_PER_STEP = 16;
const TICKS_PER_SECOND = 2000000;
const DESIRED_FPS = 58;
const TICKS_PER_CALL = parseInt(TICKS_PER_SECOND / DESIRED_FPS, 10);

const FREQUENCY_HZ = 50;
const ZEROCROSS_TO_TICKS_MULTIPLIER = TICKS_PER_SECOND / (FREQUENCY_HZ * 2)

const INITIAL_GAME = 'WPC-Fliptronics: Fish Tales';

module.exports = {
  MAXIMAL_DMD_FRAMES_TO_RIP,
  TICKS_PER_SECOND,
  DESIRED_FPS,
  TICKS_PER_CALL,
  TICKS_PER_STEP,
  FREQUENCY_HZ,
  INITIAL_GAME,
  ZEROCROSS_TO_TICKS_MULTIPLIER,
};
