'use strict';

module.exports = {
  name: 'WPC-95: Monster Bash',
  version: '1.06b',
  rom: {
    u06: 'mb_106b.bin',
  },
  switchMapping: [
    { id: 11, name: 'LAUNCH BUTTON' },
    { id: 12, name: 'DRAC STANDUP TOP' },
    { id: 13, name: 'START BUTTON' },
    { id: 14, name: 'PLUMB BOB TILT' },
    { id: 15, name: 'DRAC STANDUP BOT' },
    { id: 16, name: 'LEFT OUTLANE' },
    { id: 17, name: 'RIGHT RETURN' },
    { id: 18, name: 'SHOOTER LANE' },

    { id: 21, name: 'SLAM TILT' },
    { id: 22, name: 'COIN DOOR CLOSED' },
    { id: 23, name: 'TOMB TREASURE' },
    { id: 25, name: 'DRACULA TARGET' },
    { id: 26, name: 'LEFT RETURN' },
    { id: 27, name: 'RIGHT OUTLANE' },
    { id: 28, name: 'LEFT EJECT' },

    { id: 31, name: 'TROUGH EJECT' },
    { id: 32, name: 'TROUGH BALL 1' },
    { id: 33, name: 'TROUGH BALL 2' },
    { id: 34, name: 'TROUGH BALL 3' },
    { id: 35, name: 'TROUGH BALL 4' },
    { id: 36, name: 'RIGHT POPPER' },

    { id: 42, name: 'L FLIP OPTO' },
    { id: 43, name: 'R FLIP OPTO' },
    { id: 44, name: 'L BLUE TGT' },
    { id: 45, name: 'C BLUE TGT' },
    { id: 46, name: 'R BLUE TGT' },
    { id: 47, name: 'L FLIP PROX' },
    { id: 48, name: 'R FLIP PROX' },

    { id: 51, name: 'LEFT SLINGSHOT' },
    { id: 52, name: 'RIGHT SLINGSHOT' },
    { id: 53, name: 'LEFT JET' },
    { id: 54, name: 'RIGHT JET' },
    { id: 55, name: 'BOTTOM JET' },
    { id: 56, name: 'LEFT TOP LANE' },
    { id: 57, name: 'MIDDLE TOP LANE' },
    { id: 58, name: 'RIGHT TOP LANE' },

    { id: 61, name: 'LEFT LOOP LO' },
    { id: 62, name: 'LEFT LOOP HI' },
    { id: 63, name: 'RIGHT LOOP LO' },
    { id: 64, name: 'RIGHT LOOP HI' },
    { id: 65, name: 'CENTER LOOP' },
    { id: 66, name: 'L RAMP ENTER' },
    { id: 67, name: 'L RAMP EXIT' },
    { id: 68, name: 'C RAMP ENTER' },

    { id: 71, name: 'R RAMP ENTER' },
    { id: 72, name: 'R RAMP EXIT' },
    { id: 73, name: 'R RAMP LOCK' },
    { id: 74, name: 'DRAC POSITION 5' },
    { id: 75, name: 'DRAC POSITION 4' },
    { id: 76, name: 'DRAC POSITION 3' },
    { id: 77, name: 'DRAC POSITION 2' },
    { id: 78, name: 'DRAC POSITION 1' },

    { id: 81, name: 'UP/DN BANK UP' },
    { id: 82, name: 'UP/DN BANK DOWN' },
    { id: 83, name: 'FRANK TABLE DOWN' },
    { id: 84, name: 'FRANK TABLE UP' },
    { id: 85, name: 'L UP/DN BANK TGT' },
    { id: 86, name: 'R UP/DN BANK TGT' },
    { id: 87, name: 'FRANK HIT' },
  ],
  fliptronicsMapping: [
    { id: 'F1', name: 'R FLIPPER EOS' },
    { id: 'F2', name: 'R FLIPPER BUTTON' },
    { id: 'F3', name: 'L FLIPPER EOS' },
    { id: 'F4', name: 'L FLIPPER BUTTON' },
    { id: 'F6', name: 'UR FLIPPER BUT' },
    { id: 'F7', name: 'CENTER SPINNER' },
    { id: 'F8', name: 'UL FLIPPER BUT' },
  ],
  playfield: {
    //size must be 200x400, lamp positions according to image
    image: 'playfield-mb.jpg',
    lamps: [
      [{ x: 102, y: 214, color: 'YELLOW' }], //mosh pit
      [{ x: 39, y: 211, color: 'WHITE' }, { x: 142, y: 211, color: 'WHITE' }], //half moon
      [{ x: 80, y: 225, color: 'RED' }], //frank
      [{ x: 100, y: 226, color: 'RED' }],
      [{ x: 115, y: 171, color: 'RED' }],
      [{ x: 110, y: 189, color: 'YELLOW' }],
      [{ x: 106, y: 200, color: 'PURPLE' }],
      [{ x: 96, y: 141, color: 'ORANGE' }],

      [{ x: 135, y: 176, color: 'RED' }],
      [{ x: 91, y: 309, color: 'WHITE' }],
      [{ x: 156, y: 288, color: 'LBLUE' }],
      [{ x: 30, y: 182, color: 'WHITE' }, { x: 152, y: 184, color: 'WHITE' }],
      [{ x: 120, y: 115, color: 'WHITE' }],
      [{ x: 124, y: 203, color: 'WHITE' }],
      [{ x: 129, y: 191, color: 'WHITE' }],
      [{ x: 162, y: 162, color: 'RED' }],

      [{ x: 136, y: 225, color: 'WHITE' }, { x: 44, y: 225, color: 'WHITE' }],
      [{ x: 40, y: 169, color: 'LBLUE' }],
      [{ x: 111, y: 112, color: 'ORANGE' }],
      [{ x: 114, y: 237, color: 'RED' }],
      [{ x: 156, y: 32, color: 'ORANGE' }],
      [{ x: 138, y: 31, color: 'ORANGE' }],
      [{ x: 118, y: 29, color: 'ORANGE' }],
      [{ x: 146, y: 251, color: 'RED' }],

      [{ x: 26, y: 289, color: 'BLUE' }],
      [{ x: 10, y: 300, color: 'RED' }],
      [{ x: 35, y: 196, color: 'WHITE' }, { x: 147, y: 198, color: 'WHITE' }],
      [{ x: 89, y: 140, color: 'LBLUE' }],
      [{ x: 52, y: 172, color: 'RED' }],
      [{ x: 56, y: 188, color: 'WHITE' }],
      [{ x: 59, y: 199, color: 'WHITE' }],
      [{ x: 62, y: 213, color: 'WHITE' }],

      [{ x: 123, y: 333, color: 'RED' }],
      [{ x: 111, y: 137, color: 'WHITE' }],
      [{ x: 100, y: 341, color: 'ORANGE' }],
      [{ x: 83, y: 344, color: 'GREEN' }],
      [{ x: 70, y: 388, color: 'WHITE' }],
      [{ x: 62, y: 330, color: 'GREEN' }],
      [{ x: 100, y: 103, color: 'RED' }],
      [{ x: 52, y: 126, color: 'LBLUE' }],

      [{ x: 54, y: 283, color: 'GREEN' }],
      [{ x: 67, y: 278, color: 'WHITE' }],
      [{ x: 82, y: 272, color: 'GREEN' }],
      [{ x: 99, y: 274, color: 'WHITE' }],
      [{ x: 114, y: 279, color: 'ORANGE' }],
      [{ x: 127, y: 285, color: 'WHITE' }],
      [{ x: 171, y: 299, color: 'RED' }],
      [{ x: 91, y: 371, color: 'RED' }],

      [{ x: 62, y: 161, color: 'GREEN' }],
      [{ x: 70, y: 175, color: 'GREEN' }],
      [{ x: 74, y: 158, color: 'RED' }],
      [{ x: 73, y: 145, color: 'GREEN' }],
      [{ x: 81, y: 175, color: 'GREEN' }],
      [{ x: 86, y: 159, color: 'GREEN' }],
      [{ x: 24, y: 158, color: 'RED' }],
      [{ x: 1, y: 1, color: 'BLACK' }],

      [{ x: 19, y: 181, color: 'GREEN' }],
      [{ x: 17, y: 177, color: 'GREEN' }],
      [{ x: 15, y: 173, color: 'GREEN' }],
      [{ x: 12, y: 169, color: 'GREEN' }],
      [{ x: 100, y: 124, color: 'ORANGE' }, { x: 31, y: 359, color: 'WHITE' }],
      [{ x: 100, y: 143, color: 'YELLOW' }],
      [{ x: 190, y: 397, color: 'RED' }],
      [{ x: 9, y: 397, color: 'YELLOW' }],
    ],
    flashlamps: [
      { id: 17, x: 106, y: 2, },
      { id: 18, x: 56, y: 38, },
      { id: 19, x: 45, y: 94, }, { id: 19, x: 103, y: 65, },
      { id: 20, x: 168, y: 212, },
      { id: 21, x: 21, y: 220, },
      { id: 22, x: 135, y: 90, }, { id: 22, x: 149, y: 37, },
      { id: 23, x: 125, y: 132, },
      { id: 24, x: 80, y: 225, },
      { id: 25, x: 91, y: 309, },
      { id: 26, x: 18, y: 135, }, { id: 26, x: 173, y: 135, },
    ],
  },
  skipWmcRomCheck: true,
  features: [
    'securityPic',
    'wpc95',
  ],
  initialise: {
    closedSwitches: [
      22, 81,
      //OPTO SWITCHES: 31, 32, 33, 34, 35, 36, 74, 75, 76, 77, 78
      31, 36, 42, 43, 74, 75, 76, 77, 78,
      'F2', 'F4', 'F6', 'F8',
    ],
    initialAction: [
      {
        delayMs: 1000,
        source: 'cabinetInput',
        value: 16
      }
    ],
  }
};
