'use strict';

module.exports = {
  name: 'FreeWPC T2',
  version: 'FreeWPC 1.00',
  rom: {
    u06: 'https://s3-eu-west-1.amazonaws.com/foo-temp/ft20_32.rom',
    u14: 'https://s3-eu-west-1.amazonaws.com/foo-temp/t2_u14.l3',
    u15: 'https://s3-eu-west-1.amazonaws.com/foo-temp/t2_u15.l3',
    u18: 'https://s3-eu-west-1.amazonaws.com/foo-temp/t2_u18.l3',
  },
  playfield: {
    //size must be 200x400, lamp positions according to image
    image: 'https://s3-eu-west-1.amazonaws.com/foo-temp/playfield-t2.jpg',
  },
  switchMapping: [
    { id: 11, name: 'RIGHT FLIPPER' },
    { id: 12, name: 'LEFT FLIPPER' },
    { id: 13, name: 'START BUTTON' },
    { id: 14, name: 'PLUMB BOB TILT' },
    { id: 15, name: 'THROUGH LEFT' },
    { id: 16, name: 'THROUGH CENTER' },
    { id: 17, name: 'THROUGH RIGHT' },
    { id: 18, name: 'OUTHOLE' },
    { id: 21, name: 'SLAM TILT' },
    { id: 22, name: 'COIN DOOR CLOSED' },
    { id: 23, name: 'TICKED OPTQ' },
    { id: 25, name: 'LEFT OUT LANE' },
    { id: 26, name: 'LEFT RET. LANE' },
    { id: 27, name: 'RIGHT RET. LANE' },
    { id: 28, name: 'RIGHT OUT LANE' },
    { id: 31, name: 'GUN LOADED' },
    { id: 32, name: 'GUN MARK' },
    { id: 33, name: 'GUN HOME' },
    { id: 34, name: 'GRIP TRIGGER' },
    { id: 36, name: 'STAND MID LEFT' },
    { id: 37, name: 'STAND MID CENTER' },
    { id: 38, name: 'STAND MID RIGHT' },
    { id: 41, name: 'LEFT JET' },
    { id: 42, name: 'RIGHT JET' },
    { id: 43, name: 'BOTTOM JET' },
    { id: 44, name: 'LEFT SLING' },
    { id: 45, name: 'RIGHT SLING' },
    { id: 46, name: 'STAND RIGHT TOP' },
    { id: 47, name: 'STAND RIGHT MID' },
    { id: 48, name: 'STAND RIGHT BOT' },
    { id: 51, name: 'LEFT LOCK' },
    { id: 53, name: 'LO ESCAPE ROUTE' },
    { id: 54, name: 'HI ESCAPE ROUTE' },
    { id: 55, name: 'TOP LOCK' },
    { id: 56, name: 'TOP LANE LEFT' },
    { id: 57, name: 'TOP LANE CENTER' },
    { id: 58, name: 'TOP LANE RIGHT' },
    { id: 61, name: 'LEFT RAMP ENTRY' },
    { id: 62, name: 'LEFT RAMP MADE' },
    { id: 63, name: 'RIGHT RAMP ENTRY' },
    { id: 64, name: 'RIGHT RAMP MADE' },
    { id: 65, name: 'LO CHASE LOOP' },
    { id: 66, name: 'HI CHASE LOOP' },
    { id: 71, name: 'TARGET 1 HI' },
    { id: 72, name: 'TARGET 2' },
    { id: 73, name: 'TARGET 3' },
    { id: 74, name: 'TARGET 4' },
    { id: 75, name: 'TARGET 5 LOW' },
    { id: 76, name: 'BALL POPPER' },
    { id: 77, name: 'DROP TARGET' },
    { id: 78, name: 'SHOOTER' },
  ],
  skipWmcRomCheck: false,
  initialise: {
    closedSwitches: [ 15, 16, 17 ],
  }
};