'use strict';

module.exports = {
  name: 'WPC-95: WPC Test Fixture ',
  version: '1.2',
  pinmame: {
    knownNames: [ 'tf95_12' ],
    gameName: 'WPC Test Fixture: WPC-95',
    id: 'tf',
  },
  rom: {
    u06: 'g11_12.rom',
  },
  switchMapping: [
    { id: 11, name: 'RIGHT FLIPPER' },
    { id: 12, name: 'LEFT FLIPPER' },
    { id: 13, name: 'START BUTTON' },
    { id: 14, name: 'PLUMB BOB TILT' },
    { id: 15, name: 'SWITCH 15' },
    { id: 16, name: 'SWITCH 16' },
    { id: 17, name: 'SWITCH 17' },
    { id: 18, name: 'SWITCH 18' },

    { id: 21, name: 'SLAM TILT' },
    { id: 22, name: 'COIN DOOR CLOSED' },
    { id: 23, name: 'TICKED OPTQ' },
    { id: 25, name: 'SWITCH 25' },
    { id: 26, name: 'SWITCH 26' },
    { id: 27, name: 'SWITCH 27' },
    { id: 28, name: 'SWITCH 28' },

    { id: 31, name: 'SWITCH 31' },
    { id: 32, name: 'SWITCH 32' },
    { id: 33, name: 'SWITCH 33' },
    { id: 34, name: 'SWITCH 34' },
    { id: 35, name: 'SWITCH 35' },
    { id: 36, name: 'SWITCH 36' },
    { id: 37, name: 'SWITCH 37' },
    { id: 38, name: 'SWITCH 38' },

    { id: 41, name: 'SWITCH 41' },
    { id: 42, name: 'SWITCH 42' },
    { id: 43, name: 'SWITCH 43' },
    { id: 44, name: 'SWITCH 44' },
    { id: 45, name: 'SWITCH 45' },
    { id: 46, name: 'SWITCH 46' },
    { id: 47, name: 'SWITCH 47' },
    { id: 48, name: 'SWITCH 48' },

    { id: 51, name: 'SWITCH 51' },
    { id: 52, name: 'SWITCH 52' },
    { id: 53, name: 'SWITCH 53' },
    { id: 54, name: 'SWITCH 54' },
    { id: 55, name: 'SWITCH 55' },
    { id: 56, name: 'SWITCH 56' },
    { id: 57, name: 'SWITCH 57' },
    { id: 58, name: 'SWITCH 58' },

    { id: 61, name: 'SWITCH 61' },
    { id: 62, name: 'SWITCH 62' },
    { id: 63, name: 'SWITCH 63' },
    { id: 64, name: 'SWITCH 64' },
    { id: 65, name: 'SWITCH 65' },
    { id: 66, name: 'SWITCH 66' },
    { id: 67, name: 'SWITCH 67' },
    { id: 68, name: 'SWITCH 68' },

    { id: 71, name: 'SWITCH 71' },
    { id: 72, name: 'SWITCH 72' },
    { id: 73, name: 'SWITCH 73' },
    { id: 74, name: 'SWITCH 74' },
    { id: 75, name: 'SWITCH 75' },
    { id: 76, name: 'SWITCH 76' },
    { id: 77, name: 'SWITCH 77' },
    { id: 78, name: 'SWITCH 78' },

    { id: 81, name: 'SWITCH 81' },
    { id: 82, name: 'SWITCH 82' },
    { id: 83, name: 'SWITCH 83' },
    { id: 84, name: 'SWITCH 84' },
    { id: 85, name: 'SWITCH 85' },
    { id: 86, name: 'SWITCH 86' },
    { id: 87, name: 'SWITCH 87' },
    { id: 88, name: 'SWITCH 88' },

  ],
  skipWpcRomCheck: false,
  features: [
    'securityPic',
    'wpc95',
  ],

};
